# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339c90a1c738ab61b656d1e7952f516a059db61eb676e8a802f6e91ee2786d256c9e9f5590d1077a78141d42a2788cc30a922a2e7b682a3adb749768b578afb4

test:
  secret_key_base: 7bd3e60ca8581f6b2617085e340ea3e9f47b73dce4b960761148ec4b1af01b62181342c8deaf058304fcf025ed9e8ce24b32b01137acf881a60fd13721224c29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
